package com.funlabyrinthe.core.graphics

enum GlobalCompositeOperation:
  case SourceOver
  case SourceIn
  case SourceOut
  case SourceAtop
  case DestinationOver
  case DestinationIn
  case DestinationOut
  case DestinationAtop
  case Lighter
  case Copy
  case Xor
  case Multiply
  case Screen
  case Overlay
  case Darken
  case Lighten
  case ColorDodge
  case ColorBurn
  case HardLight
  case SoftLight
  case Difference
  case Exclusion
  case Hue
  case Saturation
  case Color
  case Luminosity
