name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        java: [ '11', '17' ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'sbt'
    - name: npm install
      run: npm install
    - name: Compile
      run: sbt -mem 4096 compile
    - name: fastLinkJS
      run: sbt -mem 2048 fastLinkJS
    - name: fullLinkJS
      run: sbt -mem 2048 fullLinkJS
    - name: core/test
      run: sbt -mem 2048 core/test
